name: C/C++ CI for State Machine

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
   
    - uses: actions/checkout@v3

    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential gcc g++ make

    # Generate configure script if needed
    - name: Generate configure script
      run: |
        if [ -f configure.ac ]; then
          autoreconf -i
        fi

    # Run the configure script if it exists
    - name: Configure
      run: |
        if [ -f configure ]; then
          ./configure
        fi

    # Build the project
    - name: Build
      run: make

    # Run tests (if you have any, otherwise modify/remove this section)
    - name: Run tests
      run: make check

    # Perform distribution check (optional, if you want to validate distribution builds)
    - name: Check distribution
      run: make distcheck

    # Run the main program with test input 
    - name: Run State Machine Program
      run: ./state_machine < test_input.txt
